#!/bin/bash
#  android-scrot takes screenshots of a android phone by adb
#  
#  Copyright 2014 Christoph Langner <mail@christoph-langner.de>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.

## Check for adb and imagemagick
command -v adb >/dev/null 2>&1 || {
	echo >&2 "Please install adb from the android sdk.  Aborting.";
	exit 1;
}

## Timestamp
TIME=$(date "+%d-%m-%Y_%H-%M-%S")

## Rename file
if [ -z "$1" ]; then
	FILENAME=android_$TIME.png
else
	FILENAME=$1_$TIME.png
fi

## Wait for phone
if [ $(adb get-state) == "unknown" ]; then
	echo Please connect your phone and activate USB-Debugging
	adb wait-for-device
fi

## Take screenshot
adb shell screencap -p | perl -pe 's/\x0D\x0A/\x0A/g' > $FILENAME
echo $FILENAME saved

## Rotate image if imagemagick is installed
command -v mogrify >/dev/null 2>&1 || {
	echo >&2 "Please install imagemagick to rotate images automatically.";
	exit 1;
}
ORIENTATION=$(adb shell dumpsys input | grep 'SurfaceOrientation' | xargs | awk '{ print $2 }')
if [ $(echo $ORIENTATION | grep 1) ]; then
	mogrify -rotate -90 $FILENAME
elif [ $(echo $ORIENTATION | grep 3) ]; then
	mogrify -rotate 90 $FILENAME
elif [ $(echo $ORIENTATION | grep 2) ]; then
	mogrify -rotate 180 $FILENAME
fi

